camera:
  index: 0

run:
  max_frames: 150
  max_seconds: 10
  condition_preview: true
  pause_after_run: true
  show_preview: true

task:
  name: object_recognition
  library: opencv
  libraries:
    - opencv
    - mediapipe
